include: package:lint/analysis_options.yaml

linter:
  rules:
    avoid_positional_boolean_parameters: false
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    sort_constructors_first: false
    prefer_single_quotes: true
    public_member_api_docs: false
    always_specify_types: true
    lines_longer_than_80_chars: true
    prefer_constructors_over_static_methods: false
    avoid_print: false
